// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodel

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type CoinPack struct {
	ID        uuid.UUID    `json:"id"`
	CoinValue int32        `json:"coin_value"`
	CoinPrice int32        `json:"coin_price"`
	Popular   sql.NullBool `json:"popular"`
	Active    sql.NullBool `json:"active"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type CoinTransaction struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Amount    int32     `json:"amount"`
	Reason    string    `json:"reason"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Note struct {
	ID                   uuid.UUID      `json:"id"`
	UserID               uuid.UUID      `json:"user_id"`
	AudioUrl             sql.NullString `json:"audio_url"`
	AudioDurationSeconds sql.NullInt32  `json:"audio_duration_seconds"`
	AudioFileSizeMb      sql.NullInt32  `json:"audio_file_size_mb"`
	Transcript           sql.NullString `json:"transcript"`
	Title                sql.NullString `json:"title"`
	WordCount            sql.NullInt32  `json:"word_count"`
	Status               string         `json:"status"`
	SearchVector         interface{}    `json:"search_vector"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

type Subscription struct {
	ID                      uuid.UUID      `json:"id"`
	UserID                  uuid.UUID      `json:"user_id"`
	RevenucatSubscriptionID sql.NullString `json:"revenucat_subscription_id"`
	RevenucatCustomerID     sql.NullString `json:"revenucat_customer_id"`
	Plan                    string         `json:"plan"`
	Status                  string         `json:"status"`
	StartDate               time.Time      `json:"start_date"`
	RenewalDate             time.Time      `json:"renewal_date"`
	ExpirationDate          time.Time      `json:"expiration_date"`
	CancellationDate        sql.NullTime   `json:"cancellation_date"`
	CancellationReason      sql.NullString `json:"cancellation_reason"`
	BillingCycleDays        int32          `json:"billing_cycle_days"`
	AmountPaid              int32          `json:"amount_paid"`
	Currency                sql.NullString `json:"currency"`
	OriginalTransactionID   sql.NullString `json:"original_transaction_id"`
	LastTransactionID       sql.NullString `json:"last_transaction_id"`
	IsDeleted               bool           `json:"is_deleted"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
}

type User struct {
	ID         uuid.UUID      `json:"id"`
	Email      string         `json:"email"`
	Password   sql.NullString `json:"password"`
	GoogleID   sql.NullString `json:"google_id"`
	UserDevice sql.NullString `json:"user_device"`
	Picture    sql.NullString `json:"picture"`
	IsActive   bool           `json:"is_active"`
	Plan       string         `json:"plan"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type UserCoin struct {
	UserID    uuid.UUID `json:"user_id"`
	Balance   int32     `json:"balance"`
	UpdatedAt time.Time `json:"updated_at"`
}
